name: MineFlag
main: net.stuntguy3000.MFPlugin
authors: [stuntguy3000, kreashenz]
version: 0.1
website: http://dev.bukkit.org/bukkit-plugins/mineflag
description: MineFlag is a CTF-style Bukkit plugin!
commands:
    MineFlag:
        description: MineFlag Main Command. Use /mf help for help.
        aliases: [mf]