name: MineFlag
main: net.stuntguy3000.MFPlugin
authors: [stuntguy3000, kreashenz]
version: 0.1
commands:
    MineFlag:
        description: MineFlag Main Command. Use /mf help for help.
        aliases: [mf]