name: MineFlag
main net.stuntguy3000.MineFlag
authors: [stuntguy3000, kreashenz, keto23]
version: maven-version-number
website: www.stuntguy3000.net
commands:
    MineFlag:
        description: MineFlag Main Command. Use /mf help for help.
        aliases: [mf]